FROM rust:1.88.0 AS builder

WORKDIR /usr/src/app
COPY . .
RUN cargo build --release --bin hetzner-proxy

FROM debian:trixie-slim AS runtime

RUN apt-get update && apt-get install -y ca-certificates libssl-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /usr/src/app/target/release/hetzner-proxy .

EXPOSE 3001

CMD ["./hetzner-proxy"]
